person-service:
  build: ./microservices/core/person-service/.
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
    - ./microservices/core/person-service/build/libs:/build
  links:
    - person-service-redis
    - eureka-service
#  log_driver: gelf
#  log_opt:
#    gelf-address: udp://${DOCKER_HOST_IP}:12201

person-recommendation-service:
  build: ./microservices/core/person-recommendation-service/.
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
    - ./microservices/core/person-recommendation-service/build/libs:/build
  links:
    - eureka-service
#  log_driver: gelf
#  log_opt:
#    gelf-address: udp://${DOCKER_HOST_IP}:12201

product-recommendation-service:
  build: ./microservices/core/product-recommendation-service/.
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
    - ./microservices/core/product-recommendation-service/build/libs:/build
  links:
    - eureka-service
#  log_driver: gelf
#  log_opt:
#    gelf-address: udp://${DOCKER_HOST_IP}:12201

person-composite-service:
  build: ./microservices/aggregate/person-composite-service/.
  hostname: person-composite-service
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
    - ./microservices/aggregate/person-composite-service/build/libs:/build
  links:
    - eureka-service
    - grafana
#  log_driver: gelf
#  log_opt:
#    gelf-address: udp://${DOCKER_HOST_IP}:12201

person-service-redis:
  image: redis:3.2.0-alpine
  ports:
    - "6379:6379"

eureka-service:
  build: ./microservices/support/eureka/.
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
    - ./microservices/support/eureka/build/libs:/build
  expose:
    - 8761
  ports:
    - "8001:8761"
#  log_driver: gelf
#  log_opt:
#    gelf-address: udp://${DOCKER_HOST_IP}:12201

#spring-boot-admin-service:
#  build: ./microservices/support/spring-boot-admin/.
#  volumes:
#    - /etc/localtime:/etc/localtime:ro
#    - /etc/timezone:/etc/timezone:ro
#    - ./microservices/support/spring-boot-admin/build/libs:/build
#  ports:
#    - "8004:8080"
#  links:
#    - eureka-service

hystrix-dashboard-service:
  build: ./microservices/support/hystrix-dashboard/.
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
    - ./microservices/support/hystrix-dashboard/build/libs:/build
  ports:
    - "8000:8080"
  links:
    - person-composite-service
    - eureka-service
    - turbine-service

turbine-service:
  build: ./microservices/support/turbine/.
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
    - ./microservices/support/turbine/build/libs:/build
  expose:
    - 8989
    - 8990
  ports:
    - "8002:8989"
    - "8003:8990"
  links:
    - eureka-service

zuul-service:
  build: ./microservices/support/zuul/.
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
    - ./microservices/support/zuul/build/libs:/build
  expose:
    - 8010
  ports:
    - "8080:8080"
  links:
    - eureka-service

grafana:
  image: kamon/grafana_graphite
  ports:
    - 80:80
    - 81:81
    - 8125:8125/udp
    - 8126:8126

probe:
  image: weaveworks/scope:0.16.0
  net: "host"
  pid: "host"
  privileged: true
  environment:
    CHECKPOINT_DISABLE: "true"
  labels:
    - "works.weave.role=system"
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock:rw"
  command:
    - "--probe.docker"
    - "true"
