person-service:
  build: ./microservices/core/person-service/.
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
    - ./microservices/core/person-service/build/libs:/build
  ports:
    - "8080:8080"
  links:
    - person-service-redis
person-recommendation-service:
  build: ./microservices/core/person-recommendation-service/.
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
    - ./microservices/core/person-recommendation-service/build/libs:/build
  ports:
    - "8081:8080"
product-recommendation-service:
  build: ./microservices/core/product-recommendation-service/.
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
    - ./microservices/core/product-recommendation-service/build/libs:/build
  ports:
    - "8082:8080"

person-composite-service:
  build: ./microservices/aggregate/person-composite-service/.
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
    - ./microservices/aggregate/person-composite-service/build/libs:/build
  ports:
    - "8083:8080"
  links:
    - person-service
    - person-recommendation-service
    - product-recommendation-service

person-service-redis:
  image: redis:3.0.7
  ports:
    - "6379:6379"

hystrix-dashboard-service:
  build: ./microservices/support/hystrix-dashboard/.
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
    - ./microservices/support/hystrix-dashboard/build/libs:/build
  ports:
    - "8090:8080"
  links:
    - person-composite-service
