info:
  build:
    name: "${name}"
    description: "${description}"
    version: "${version}"
    created_at: "${new Date()}"
  version: "${version}" # Specifically added for Spring-boot-admin
spring:
  redis:
    host: person-service-redis