influxsrv:
  image: "tutum/influxdb:0.8.8"
  ports:
    - "8093:8083"
    - "8096:8086"
  expose:
    - "8090"
    - "8099"
  environment:
    PRE_CREATE_DB: cadvisor
cadvisor:
  image: "google/cadvisor:0.14.0"
  volumes:
    - "/:/rootfs:ro"
    - "/var/run:/var/run:rw"
    - "/sys:/sys:ro"
    - "/var/lib/docker/:/var/lib/docker:ro"
  links:
    - influxsrv
  ports:
    - "9001:8080"
  command: "-storage_driver=influxdb -storage_driver_db=cadvisor -storage_driver_host=influxsrv:8086"
grafana:
  image: "grafana/grafana:2.0.2"
  ports:
    - "3000:3000"
  environment:
    INFLUXDB_HOST: influxsrv
    INFLUXDB_PORT: 8086
    INFLUXDB_NAME: cadvisor
    INFLUXDB_USER: root
    INFLUXDB_PASS: root
  links:
    - influxsrv
